### ISSUE TITLE
Is executing external process in request handler good approach?

### ISSUE THREAD

**Issue by KumKeeHyun** [SSU-NC/PDK#11]
@yoonje
We need to run kafka consumer process dynamically when new service request comes in.
I'm testing various methods. this is one of them.

```go
// main.go (web service)
var cmdMap = map[string]*exec.Cmd{}

func main() {
	r := gin.Default()

	r.GET("/:id/run", func(c *gin.Context) { // new service request 
		id := c.Param("id")
		if _, exist := cmdMap[id]; exist {
			c.JSON(http.StatusBadRequest, gin.H{"error": "already exist"})
		} else {
			cmd := exec.Command("back/ground", id) 
			cmd.Stdout = os.Stdout

			err := cmd.Start() // run new consumer process
			if err != nil {
				c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
			} else {
				cmdMap[id] = cmd // store cmd 
				c.JSON(http.StatusOK, gin.H{"error": "none"})
			}
		}

	})
	r.GET("/:id/stop", func(c *gin.Context) { // drop service request
		id := c.Param("id")
		if _, exist := cmdMap[id]; !exist { // check process is exist
			c.JSON(http.StatusBadRequest, gin.H{"error": "not exist"})
		} else {
			cmd := cmdMap[id]
			err := cmd.Process.Kill() // stop consumer process
			if err != nil {
				c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
			} else {
				delete(cmdMap, id)
				c.JSON(http.StatusOK, gin.H{"error": "none"})
			}
		}

	})

	log.Fatal(r.Run(":1234"))
}
```
```go
// back/ground (kafka consumer)
func main() {
	id := os.Args[1]
	tick := time.Tick(3 * time.Second)
	for {
		select {
		case <-tick:
			fmt.Printf("%s tick\n", id)
		}
	}
}
```
it worked well but I'm not sure it's a good idea.
Is there any other good way? (consume data -> index elasticsearch)

**Comment by yoonje** [comment]
Kafka's performance does not depend on the number of consumers. It is the number of partitions and the number of consumer groups that affect Kafka's performance. Simply increasing the consumer process does not improve performance.

In my opinion, it would be better to develop one static process that is being consumed and one static process that is being produced, and then freely set and use it according to the system design required by the PDK user.

**Comment by KumKeeHyun** [comment]
kafka/pipe.go serves as an interface between Kafka and ElasticSearch and functions for data processing in one process. The function for the consumer group is considering using multiple goroutine consumers in the pipe process.

If the functionality for PDK is added, the size of the pipe process is likely to increase.
