### ISSUE TITLE
application architecture

### ISSUE THREAD

**Issue by KumKeeHyun** [SSU-NC/PDK#16]
The current app is a poor mvc pattern. I didn't like the current structure, so I studied clean archtecture and rewrote it.
* clean archtecture : https://k-elon.tistory.com/38

* rewrote test version : https://github.com/KumKeeHyun/gin-clean-arch
What do you think about this?

**Comment by yoonje** [comment]
I think it would be a good idea to have a deep discussion with someone doing the web frontend development.
