### ISSUE TITLE
alarm service

### ISSUE THREAD

**Issue by iamhge** [SSU-NC/PDK#18]
Register Alarm Service
1. Select sensor
2. Set time range which user want to be alert
3. Select values
    * User set the sensor's values' range
4. Set the message
5. Add e-mail

Frontend will make this service by new page.
I have to...
* Update navigation field
* make ALARM page
    * RegisterAlarm.js
    * ManagementAlarm.js
    * ...

**Comment by KumKeeHyun** [comment]
This issue has been moved and integrated into [issue-31].
