### ISSUE TITLE
Sensor value data enhancement design

### ISSUE THREAD

**Issue by KumKeeHyun** [SSU-NC/PDK#4]
센서에서 생성되는 데이터는 가벼울수록 좋으므로 생성, 저장되는 데이터를 **센서 노드 정보**와 **센서 값 정보**로 나누어 저장하려 합니다.
- 노드 정보 : 사용자가 웹에서 등록하는 노드들의 정보
    - nodeID : 각 노드들을 식별할 수 있는 ID
    - location : 노드가 설치된 위치정보
    - installDate : 노드가 설치된 날짜
    - sensorList : 해당 노드에서 어떤 센서를 사용하고 있는지
    - 등등
- 센서 정보 :  사용자가 웹에서 등록하는 센서들의 정보
    - sensorID : 각 센서를 식별할 수 있는 ID
    - sensorModel : 센서 모델 정보
    - criticalPoint : 이상징후를 판단할 수 있는 기준
    - 등등
- 센서 값 정보 : 실제 노드에서 mptt 프로토콜로 전송되는 데이터
    - nodeID : 해당 센서값을 생성해낸 노드의 ID
    - sensorID : 노드에 부착된 센서들의 종류를 식별할 수 있는 ID
    - sensorValue : 해당 센서에서 측정된 값
    - timestamp : 해당 센서값이 측정된 시간

최종적으로 Elasticsearch에 데이터를 저장하기 위해서는 앞선 데이터들을 조인하는 데이터 보강이 필요합니다.
데이터 보강 처리를 통해 웹에서 등록한 센서 정보만 활용할 수 있도록 필터링하는 기능도 수행하고자 합니다.

데이터 보강이 이루어지는 지점에 대한 논의가 필요합니다.

1. 카프카에서 KStrema, KTable을 이용한 조인연산
    - 조인결과가 저장되는 토픽이 추가로 필요함, 카프카의 I/O 연산이 많아짐
    - 조인 연산을 수행하는 스트림 어플리케이션을 동적으로 생성, 삭제하는 방법을 모름, Java로 작성해야 함
    - 데이터 보강처리를 하지 않은 raw한 센서데이터를 추가적으로 활용 가능
1. 카프카 컨슈머에서 조인연산
    - 카프카의 I/O 연산이 적어 카프카 브로커의 부담이 적음
    - 카프카 컨슈머 API를 지원하면 해당 언어로 구현 가능
    - 카프카에 유효하지 않은 데이터를 추가적으로 저장하여 카프카 자원 낭비

**Comment by KumKeeHyun** [comment]
* schema 
```SQL
CREATE TABLE nodes ( 
    gorm.Model,
    name VARCHAR(32) NOT NULL,
    uuid CHAR(20) NOT NULL UNIQUE,
    lacation VARCHAR(64) NOT NULL
)

CREATE TABLE sensors (
    gorm.Model,
    name VARCHAR(32) NOT NULL,
    uuid CHAR(20) NOT NULL UNIQUE,
    numofvalue integer NOT NULL,
)

CREATE TABLE nodesensor (
    gorm.Model,
    nuuid CHAR(20) NOT NULL,
    suuid CHAR(20) NOT NULL,
    FOREIGN KEY (nuuid)
    REFERENCES nodes(uuid)
    ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (suuid)
    REFERENCES sensors(uuid)
    ON UPDATE CASCADE ON DELETE CASCADE,
)

CREATE TABLE sensorvalues (
    gorm.Model,
    suuid CHAR(20) NOT NULL,
    valuename VARCHAR(32) NOT NULL,
    index integer NOT NULL,
    FOREIGN KEY (suuid)
    REFERENCES sensors(uuid)
    ON UPDATE CASCADE ON DELETE CASCADE,
)
```

* Data(send to kafka)
```json
{
    "n_uuid" : ";zkvhr",
    "s_uuid" : "aoviwkj...",
    "value" : {
        "v1" : 123,
        "v2" : 43,
        "v3" : 533
    },
    "timestamp" : "2020-11-30"
}
```

**Comment by KumKeeHyun** [comment]
## test api
### node
* GET /node/regist
    * 등록된 노드, 센서 정보

* POST /node/regist -d {"name" : "nv", "location" : "lv"}
    * 노드 정보 등록
    * name : 등록할 노드의 이름
    * location : 등록할 노드의 위치정보
* POST /node/sensor -d {"n_uuid" : "nv", "s_uuid" : "sv"}
    * n_uuid : 노드의 식별자(uuid) (GET /node/regist 에서 알 수 있음)
    * s_uuid : 센서의 식별자(uuid) (GET /sensor/regist 에서 알 수 있음)

### sensor
* GET /node/regist
    * 등록된 센서 자세한 정보

* POST /node/regist -d {"name" : "nv", "num_of_values" : 2, "value_names" : ["v1", "v2"]}
    * 센서 정보 등록
    * num_of_values : 센서의 측정 값 개수
    * value_names : 센서 측정값들의 이름들 (아두이노에서 보내는 순서대로)

**Comment by yoonje** [comment]
@KumKeeHyun 
Which relational database are you going to use? MySQL? PostgresSQL?

**Comment by KumKeeHyun** [comment]
@yoonje
We are using MySQL

Schema is test version

**Comment by yoonje** [comment]
@KumKeeHyun 
Okay.
