### ISSUE TITLE
Which kind Kafka?

### ISSUE THREAD

**Issue by yoonje** [SSU-NC/PDK#6]
- [confluent kafka](https://www.confluent.io/?utm_medium=sem&utm_source=google&utm_campaign=ch.sem_br.brand_tp.prs_tgt.confluent-brand_mt.xct_rgn.apac_lng.eng_dv.all&utm_term=confluent%20kafka&creative=&device=c&placement=&gclid=CjwKCAjwxqX4BRBhEiwAYtJX7VHy15B5XyqYjDF1yZFjUI97_qGfrp8K3bO1K0aP30W5p-QzkpgYcBoCtfMQAvD_BwE)
- [apache kafka](https://kafka.apache.org/)

confluent kafka more fast but requires a separate c language library.

**Comment by KumKeeHyun** [comment]
confluent kafka is used for testing

**Comment by yoonje** [comment]
OK! I think `apache kafka` is better.
